build:
	g++ -std=c++11 -o ann_to_snn ann_to_snn.cpp \
	-I/Library/Frameworks/Python.framework/Versions/3.8/include/python3.8 \
	-L/Library/Frameworks/Python.framework/Versions/3.8/lib/ \
	-lpython3.8

clean:
	rm -f ann_to_snn